# Site settings. Values here are available in templates as {{ site.* }}.
locale      : "en-US"
title       : "Jacob Morrison"
name        : "Jacob Morrison"
description : "Jacob Morrison is a Ph.D. student at the University of Washington and student researcher at Ai2, building open language models and studying the environmental and societal impacts of AI."
url         : "https://jacobmorrison.com"
timezone    : "America/Los_Angeles"

markdown: kramdown

include:
  - _pages

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
